# production only prints info and above. development also prints debug
environment: production
eth_rpc_url: http://anvil:8545
eth_ws_url: ws://anvil:8545
# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: 0.0.0.0:8090
bls_public_key_compendium_address: 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44