# this sets the logger level (true = info, false = debug)
production: false

operator_address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

# EigenLayer Slasher contract address

# This is the address of the contracts which are deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/credible_squaring_avs_deployment_output.json
# TODO(samlaf): automate updating these addresses when we deploy new contracts
avs_registry_coordinator_address: 0x7969c5ed335650692bc04293b07f5bf2e7a673c0
operator_state_retriever_address: 0x4c5859f0f772848b2d91f1d83e2fe57935348029

# ETH RPC URL
eth_rpc_url: http://anvil:8545
eth_ws_url: ws://anvil:8545

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/ecdsa_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local ecdsa key file
ecdsa_private_key_store_path: tests/keys/test.ecdsa.key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# We are using bn254 curve for bls keys
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: tests/keys/test.bls.key.json

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: incredible-squaring-aggregator:8090

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: 0.0.0.0:9090
enable_metrics: true
node_api_ip_port_address: 0.0.0.0:9010
enable_node_api: true

# we need to register the operator on startup when running the docker compose file
# because unfortunately we cannot register the operator previously and save it in the anvil json file
# This is because anvil only dumps the state, and not the receipt tree, so when we restart anvil with
# the registered operator, it's blspubkey registering event with the compendium is not present anymore,
# and so the aggregator can't find it.... very annoying
register_operator_on_startup: true
# address of token to deposit tokens into when registering on startup
# addresses.erc20MockStrategy in tests/anvil/credible_squaring_avs_deployment_output.json
token_strategy_addr: 0x2b961e3959b79326a8e7f64ef0d2d825707669b5